"""
Version information for the Kalinka server.

Two distinct, unrelated versions live here:

* The **package version** (:func:`get_version`) is generated by setuptools_scm
  from the ``kalinka-v*`` git tag and written to ``_version.py`` at build time.
* The **REST/WS API version** (:data:`REST_API_VERSION` /
  :func:`get_rest_api_version`) is the client-facing HTTP/WebSocket contract
  version. It is hardcoded and bumped by hand when that API changes — it is not
  derived from git or the package version. It is exposed via ``/server/version``
  and mDNS discovery so clients (e.g. the frontend app) can check compatibility.
  (Distinct from ``kalinka_plugin_sdk.__version__``, the server↔plugin
  contract, which the plugins' ``kalinka-plugin-sdk`` pins gate at install and
  their ``REQUIRES_SDK`` specifiers at load.)
"""

# Written by setuptools_scm at build time; absent only in an unbuilt source tree.
try:
    from ._version import version as __version__
except ImportError:
    __version__ = None


def get_version() -> str:
    """Return the package version (``X.Y.Z`` or a ``X.Y.Z.devN+…`` dev form).

    Comes from ``_version.py`` (setuptools_scm / the ``kalinka-v*`` tag). Falls
    back to ``"0.0.0"`` only when run from a source tree that was never built.
    """
    if __version__ and __version__ != "0.0.0+unknown":
        return __version__
    return "0.0.0"


# Client-facing REST/WebSocket API contract version. Bump deliberately when the
# client API changes; independent of the package version above. Distinct from
# kalinka_plugin_sdk.__version__ (the server<->plugin SDK contract).
# 0.2: playback moved to renderers — output selection lives behind /renderer/*,
# and the built-in local-alsa device is gone.
# 0.3: /queue/ws reports the renderer topology — renderers_changed and
# current_renderer_changed events, and the matching replay state fields.
# 0.4: playback state carries the output device (audio_info.output) and the
# device volume names the backend it is applied by.
# 0.5: renderer records say whether this Core can drive them (compatible)
# and whether they can install a release of themselves (upgrade_supported),
# which POST /renderer/{id}/upgrade asks them to do; playback state names
# the URL the renderer is fetching (stream_url).
# 0.6: search is asked one source at a time — `sources` is required on
# /search/matches and /ai_search, /ai_search takes a single source and no
# longer pages, and module records name the optional calls they answer
# (capabilities).
# 0.7: GET /server/config never carries a credential (a password-widget
# field): `values` omits it, `secrets_set` names the ones holding a value,
# and the schema gives such a field no default. /server/logs/export prepares
# an archive of the server's recent logs, which /server/logs/export/download
# serves. A config value may be a list of records (localfiles'
# music_sources), described in a module's or section's `collections`: its
# credentials are left out of `values` and named in `secrets_set` by the
# entry's id (`<path>.<id>.<field>`), and writing the list back without one
# keeps it while the entry is for the same server and user. An entry that now
# names another server or user, or is of another kind, draws an error at the
# credential it left out, in the dry run and the save alike, and must send it
# again. A successful PUT /server/config returns the resulting `secrets_set`.
# A collection's `replaces` names the older fields it stands for, which a
# client showing it hides. localfiles' music_folders is its local sources'
# folders; writing either list updates the other. A /server/modules entry
# carries the module's `icon` (a material icon name, or null), which a client
# draws in place of its letter badge.
# 0.8: who drives the output is `playback_control`: in the /queue/ws and
# /queue/events replay, in playback_control_changed (sent ahead of the
# state_changed it explains), and from GET /queue/control. Its mode is "queue"
# while the play queue plays, or "exclusive" with the plugin_id and title
# ("Qobuz Connect") of an input plugin that took the renderer to play outside
# the queue, as a Connect receiver does. Under "exclusive" the queue plays
# nothing and keeps its contents; state_changed and GET /queue/state describe
# the plugin's playback, with current_track the plugin's and index null. pause,
# seek, next and prev go to the plugin; play gives the renderer back to the
# queue and plays; stop gives it back without playing. Queue edits and
# set_playback_mode still apply to the queue. PUT /renderer/active moves the
# plugin's playback, which carries on where it had reached; the speaker test
# ends it.
# 0.9: read-only /server/plugins inventory separates installation origin,
# catalog identity verification and update eligibility. Public HTTPS catalogs
# are browsable with metadata-only host compatibility checks; signature
# verification and installation remain unavailable. /server/version advertises
# the implemented capabilities.
# 0.10: a settings field may be `readonly` without being `dynamic`; PUT
# /server/config refuses such a path with 400. base_config.server.demo_mode
# marks a public demo server: it answers every write outside /queue/* and PUT
# /device/set_volume, the settings dry run included, with 403
# {"detail": {"code": "demo_read_only", "message"}}, refuses /renderer/ws,
# reports upgrade_supported false, carries a General-page banner, and plays
# through the simulated renderer `demo-output`, which reports a length and no
# format. It answers a POST /queue/add past its queue limit with 409
# `demo_queue_full`, and a visitor's changes past its rate limit with 429
# `demo_rate_limited` and Retry-After.
# 0.11: /renderer/list reports `local`, proved by the optional machine identity
# in renderer Hello. A manual server upgrade vacates busy renderers, reports
# STOPPED without a playback fault, and answers `upgrading` while their installs
# finish. Core waits for confirmed target versions before starting its installer;
# the packaged renderer on its own host is covered by that installer. Refusals
# name the renderer and reason. Automatic upgrades still defer busy renderers.
# Also 0.11: a catalog whose preview type is `folder` is a folder of a file-backed
# source, listing its subfolders and then the tracks directly in it; adding
# one takes every track below it, subfolders included, in the order the
# folders list them. My Library is now such a catalog, `files`:
# the music sources, or the one source's folders, under its playlists. A
# second card, `recent`, lists the newest albums and singles. The per-kind
# shelves are no longer listed, though their catalogs still answer. POST
# /queue/add refuses an add that would take the queue past 1000 tracks with
# 409 {"detail": {"code": "queue_full", "message"}}, adding nothing.
# 0.12: POST /queue/replace takes the body /queue/add takes, without an index,
# and replaces the queue with those tracks in one request. Only the new tracks
# count against the queue limit; past it the answer is 409 with /queue/add's
# code (`queue_full`, or `demo_queue_full` on a demo server) but a message of
# its own, which does not suggest clearing the queue, and the queue is left as
# it was. Ids that come to no tracks, an empty album or folder or ids no
# source still has, are answered 422 {"detail": {"code": "no_tracks",
# "message"}}, also leaving the queue as it was. A server before 0.12 answers
# the route with 405 from its browser-player mount at "/", or with 404 where it
# has no such mount.
# 0.13: optional packages install from wheels only. A failed entry in GET
# /server/optional_packages' last_install results whose package has no wheel
# for the server's Python and architecture carries a `reason` naming all three.
REST_API_VERSION = "0.13"


def get_rest_api_version() -> str:
    """Return the client-facing REST/WS API version (see :data:`REST_API_VERSION`)."""
    return REST_API_VERSION
